### ISSUE TITLE
create node with login but access deny

### ISSUE THREAD

**Issue by chzhcpu** [titobrasolin/Drupal7.Services#1]
I have logged in and creatnode , but throw a exception: access deny:
here is my code:

```
        DrupalServices service = new Drupal7.Services.DrupalServices("http://**********");
        bool login = service.Login("*******", "*******");
        XmlRpcStruct node = service.NodeRetrieve(1);
        if (service.IsLoggedIn)
        {
            node["title"] = "123";
            service.NodeUpdate(node);
        }
```

**Comment by titobrasolin** [comment]
@chzhcpu Maybe your user's permissions are insufficient. Anyhow I'll investigate and let you know ASAP

**Comment by chzhcpu** [comment]
Thinks for your kind replay.
Would you please give me an example of create or update a node?

**Comment by titobrasolin** [comment]
@chzhcpu Your code looks quite fine, but I think there's some issue with the XmlRpcStruct class.
Please try these:
1) To update the node, do _not_ assign a new value to its fields but remove and add them back like this:

``` csharp
    var node = service.NodeRetrieve(1);
    var oldTitle = node["title"];
    node.Remove("title");
    node["title"] = oldTitle + " (UPDATED)";
    node = service.NodeUpdate(Convert.ToInt32(node["nid"]), node);
```

2) You can "clone" a node like this (at first i thought it was necessary to remove the "nid", in fact it is not):

``` csharp
    var node = service.NodeRetrieve(1);
    var clone = service.NodeCreate(node);
```

You can combine 1) and 2) of course:

``` csharp
    var node = service.NodeRetrieve(1);
    node.Remove("title");
    node["title"] = "This is a clone";
    var clone = service.NodeCreate(node);
```

By the way, remember to check that your user has update and create permissions, and that the node you are retrieving actually exists.

**Comment by titobrasolin** [comment]
Update: "cloning" a node was in fact easier than i thought, I just updated the comment above accordingly.

**Comment by chzhcpu** [comment]
Thanks a lot. 
It works well.

**Comment by ibuildit** [comment]
I have the same access denied issue, my site is accessed as anonymous even after sucessful login (see the other issue I created)

**Comment by ibuildit** [comment]
Correction - if I DO NOT login I can access nodes.

When I AM LOGGED IN, I can't.

**Comment by ibuildit** [comment]
It also does not make any difference if I tick the session authentication in services config or not.

**Comment by ibuildit** [comment]
The access denied issue is resolved on my end (human error).
