### ISSUE TITLE
How assign values to a term reference field

### ISSUE THREAD

**Issue by chzhcpu** [titobrasolin/Drupal7.Services#2]
I have defined a new node type named "News" with a  term reference field. How do I assign values to the term reference field when I create a news node?

**Comment by titobrasolin** [comment]
It may depend on the form widget for the field. For example, if you are using an autocomplete term widget (tagging) you can try this:

``` csharp
    var drupal = new Drupal7.Services.DrupalServices("...");
    var isLoggedIn = drupal.Login("...", "...");

    var node = new Hashtable
    {
        { "type", "news" },
        { "title", "MyNews" },
        { "field_tags", new Hashtable { { "und", "MyTag,MyTag2,MyTag3" } } }
    };
    var nid = drupal.NodeCreate(node);
```

**Comment by ibuildit** [comment]
chzhcpu: see this: [https://github.com/titobrasolin/Drupal7.Services/issues/12](https://github.com/titobrasolin/Drupal7.Services/issues/12)

and this [https://github.com/titobrasolin/Drupal7.Services/issues/13](https://github.com/titobrasolin/Drupal7.Services/issues/13)

You can create an XMLRpcStruct directly and place that as a value inside the IDictionary and then build the XMLRpcStruct you send back to Drupal.

**Comment by titobrasolin** [comment]
I'm closing this old issue, an answer can be found here: https://github.com/titobrasolin/Drupal7.Services/wiki/How-to-assign-values-to-a-term-reference-field

Thank you @chzhcpu and @ibuildit
