### ISSUE TITLE
 retrieve nodes with a field filter

### ISSUE THREAD

**Issue by chzhcpu** [titobrasolin/Drupal7.Services#3]
How can I get a list of all the node with specified type, and how to retrieve nodes with a field filter?
Thanks.

**Comment by titobrasolin** [comment]
Here is how you can get a list of nodes with specified type:

``` csharp
    string url = "http://example.com/services/xmlrpc";
    var drupal = new Drupal7.Services.DrupalServices(url);

    int page = 0;
    string fields = "*";
    int page_size = 20;

    var parameters = new XmlRpcStruct ();
    parameters ["type"] = "article"; // Or "blog", "page", ...

    var nodes = drupal.NodeIndex (page, fields, parameters, page_size);
```

As far as I know you can't get a list of _all_ nodes, but there is no limit to `page_size` as long as your user has 'perform unlimited index queries' permission, see also: http://cgit.drupalcode.org/services/tree/services.module?h=7.x-3.x#n921

You can also fetch multiple types, like this:

``` csharp
    parameters ["type"] = "article,blog,page";
```

**Comment by titobrasolin** [comment]
For the field filter, let me think a little about that... (I'll answer as soon as possible)

**Comment by titobrasolin** [comment]
As far as I can see filtering by a field is not possible with the node resource that comes with the services module, so I just pushed an update to my library with partial support for https://www.drupal.org/project/services_entity

For example, fetch max 10 nodes of type "blog" that reference term id 1 (the field is named "field_tags")

``` csharp
    var drupal = new Drupal7.Services.DrupalServices("http://localhost/drupal/xmlrpc");

    string fields = "*";
    var parameters = new Hashtable();
    parameters["type"] = "blog";
    parameters["field_tags"] = 1;
    int page = 0;
    int pagesize = 10;

    var nodes = drupal.EntityNodeIndex(fields, parameters, page, pagesize);
```

You can add conditions to parameters for whatever field you want.

**Comment by chzhcpu** [comment]
Thanks for all your kind replay.

**Comment by ibuildit** [comment]
Hi Tito.

Thank you so much for building this, it's an impressive tool.

How ever, I'm confused about something that I'm stuck at.

In your above example... how can I use the "nodes" var? I can't seem to understand how to actually get the data out of it.

Could you please provide a quick example?

Thanks!

**Comment by titobrasolin** [comment]
Hi @ibuildit. The `NodeIndex` method returns an array of `XmlRpcStruct` that is a subclass of `Hashtable` (a collection of key/value pairs).

As a first test, I suggest you to try and print the contents of the array in a readable form. Here is a handy package: https://www.nuget.org/packages/ObjectPrinter/

It will provide you with useful extension methods, e.g. `DumpToString`:

```
using ObjectPrinter;
// ...
System.Diagnostics.Debug.Print(nodes.DumpToString());
```

The output should look like this:

```
[XmlRpcStruct[]]: hashcode { 33420276 }
{
    [XmlRpcStruct]: hashcode { 1865637092 }
    {
        nid : 35
        promote : 1
        changed : 1448184993
        type : article
        created : 1447188391
        comment : 2
        title : This is a clone
        sticky : 1
        tnid : 0
        uid : 1
        vid : 35
        status : 1
        translate : 0
        language : und
    }
    [XmlRpcStruct]: hashcode { -1704645157 }
    {
        nid : 1
        promote : 1
        changed : 1448188584
        type : article
        created : 1417024292
        comment : 2
        title : Title (UPDATED)
        sticky : 1
        tnid : 0
        uid : 1
        vid : 1
        status : 1
        translate : 0
        language : und
    }
}
```

As a small example, let's print all the titles out:

```
foreach (var node in nodes) {
  System.Diagnostics.Debug.Print(node["title"].ToString());
}
```

This doesn't cover everything, but I hope it's a good starting point for you. Let me know if you need more help.

**Comment by titobrasolin** [comment]
I pushed an update with a new class (`BaseNode`) and an `IDictionary` extension method: it's not a complete solution, just an example of an easy method to map an `IDictionary` item to a class instance (take a look at the code for the details).

Sample usage:

``` csharp
var items = drupal.NodeIndex(0, 20);
var node = items[0].ToBaseNode();

System.Diagnostics.Debug.Print("First node title: " + node.title);
System.Diagnostics.Debug.Print("Created on: " + new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc).AddSeconds(node.created).ToLocalTime());
```

You can convert the whole array easily with some Linq:

``` csharp
var items = drupal.NodeIndex(0, 20);
var nodes = items.Select(ExtensionMethods.ToBaseNode).ToArray();

System.Diagnostics.Debug.Print(nodes.DumpToString());
```

By the way, I converted the timestamp the old way but on recent version of the .NET framework you have specific methods to handle Unix timestamps.

**Comment by ibuildit** [comment]
That's beautiful. Thank you for that.

I will let you know if I come across any suggestions for improvement as I
go along.

/J

**Comment by ibuildit** [comment]
*Just noted something:*

In the latest Visual Studio you must add System.Web.Extensions as a
Reference to the project in order to access
System.Web.Script.Serialization.JavaScriptSerializer (note the path is
different from System.Web.Script.JavaScriptSerializer in your code)


So far it's going pretty well, I like the concept of the BaseNode to cater
to different nodetypes.

I get into trouble again when I try to access the data from a custom field
using the ToBaseNode() method.

I have added my field in the BaseNode class, but I guess this needs to be
deserialized again somehow?


field_risk_trailing_trigger_2 : [XmlRpcStruct]: hashcode { 20234383 }
{
und : [Object[]]: hashcode { 20234383 }
{
1300
}
}

**Comment by ibuildit** [comment]
I think I figured it out,

/J

**Comment by ibuildit** [comment]
Nope, didn't work. Any ideas on how to access these multi level areas? i.e.
put them in a WriteLine();


*field_account_risk_profile : [XmlRpcStruct]: hashcode { 20915929 }*
* {*
* und : [Object[]]: hashcode { 20915929 }*
* {*
* 30*
* }*
* }*


and

*field_risk_welcome_message : [XmlRpcStruct]: hashcode { 47145209 }*
* {*
* und : [Object[]]: hashcode { 47145209 }*

* {*
* [XmlRpcStruct]: hashcode { 757602046 }*
* {*
* value : A MESSAGE!*
* format : *
* safe_value : A MESSAGE!*
* }*
* }*
* }*

**Comment by ibuildit** [comment]
I opened a separate issue for this: https://github.com/titobrasolin/Drupal7.Services/issues/6

**Comment by titobrasolin** [comment]
I'm closing this old issue, after adding a new page to the Wiki: https://github.com/titobrasolin/Drupal7.Services/wiki/How-to-retrieve-a-list-of-nodes

Thank you @chzhcpu and @ibuildit
