### ISSUE TITLE
Session handling

### ISSUE THREAD

**Issue by ibuildit** [titobrasolin/Drupal7.Services#4]
Hi!

Is there a recommended way on how to send the session cookie with a request or is this taken care of automatically after performing LoginUser()

i.e. if I want to load a node after logging in, should it be enough to just call NodeRetrieve()?

When I do it, I can only access public content, not content restricted to a role.

More specifically, the DrupalSessionObject returned is empty when running SystemConnect();

IsLoggedIn also returns false.

But I do get the user data from the LoginUser, i.e. var blabla = UserLogin("user", "pass");
But I don't know how to make it so the commands I enter after this runs as logged in user and not anonymous. I thought Thanks!

**Comment by ibuildit** [comment]
More specifically, the DrupalSessionObject returned is empty when running SystemConnect();

But I do get the user data from the LoginUser, but I don't know how to make it so the commands I enter after this runs as logged in user and not anonymous. Thanks!

**Comment by titobrasolin** [comment]
Hi @ibuildit.

Try using the `public bool Login(string username, string password)` method of the `DrupalServices` class: it wraps around `UserLogin`, returns `true` on success and initializes a private session object that contains the "X-CSRF-Token".

By the way, I used to have big troubles because of this nasty old `CookieContainer` bug: http://social.msdn.microsoft.com/Forums/en-US/ncl/thread/c4edc965-2dc2-4724-8f08-68815cf1dce6

I don't know if the .NET 4.0 fix has been backported to 3.5 and 2.0, but if you still have strange problems you might want to consider doing a HTTP traffic analysis with Wireshark or http://www.pocketsoap.com/tcptrace/

**Comment by ibuildit** [comment]
Hi, thank you. 

When I use the Login(), I do get "true" from IsLoggedIn(),
but SystemConnect().DumpToString() still returns null on everything and I also can not pull my own useraccount or nodes I have created for that user.

When I use UserLogin() I get everything I expect to see, name, mail, in the DrupalSessionObject that comes back with it.

Not sure how to proceed from here, really all I'm doing is the drupal.Login() and then a drupal.UserRetreive(uid), and that should be it, and and as proof that I can pull data, I see that the code works if I let anonymous users access everything on Drupal.

I'm using the latest Visual Studio and .NET 4.0. Will look into traffic analysis, but please let me know if I'm missing something obvious.

**Comment by ibuildit** [comment]
The bool Login() doesn't return any Drupal session object, so the UserLogin() would be the best to get working so you have the user object avaliable, and also make SystemConnect() return a new object of the same stuff. I'm piecing together how this is done when I have time, still not really up to speed on it.

**Comment by titobrasolin** [comment]
The `bool Login()` method saves the session data returned by `UserLogin()` into a private field for internal use, that's why it's the recommended method to use.

Anyway, I just exposed the session data through a public property in commit 229d465

Now you can access it if you need to:

``` csharp
using Drupal7.Services;
using ObjectPrinter;
using System.Diagnostics;

var drupal = new DrupalServices("http://www.example.net/services/xmlrpc");
if (drupal.Login("username", "password"))
{
    Debug.Print(drupal.SessionData.DumpToString());
}
else
{
    Debug.Print(drupal.ErrorMessage);
}
```

**Comment by ibuildit** [comment]
That's great and it works too.

Are you sure that the session data is transmitted back to drupal on
requests?

I still can't seem to access role-restricted data.

**Comment by titobrasolin** [comment]
@ibuildit I just did a quick test and everything works as expected. I enabled 'View own unpublished content' for the authenticated user, then created (but not published) a new node.

I can definitely access the node _only_ after logging in:

``` csharp
using ObjectPrinter;
using Drupal7.Services;
using System.Diagnostics;

var drupal = new DrupalServices ("http://www.example.net/services/xmlrpc");

var item = drupal.NodeRetrieve (1);
Debug.Print (drupal.ErrorMessage); // [403] Access denied for user anonymous

drupal.Login ("username", "password");
item = drupal.NodeRetrieve (1);
Debug.Print (item.DumpToString ()); // Prints out the node.
```

**Comment by ibuildit** [comment]
It works now. I had forgotten to enable Session Authentication in Services
configuration ("Edit"), I'll add it to the wiki posts later.
