### ISSUE TITLE
Hello Tito

### ISSUE THREAD

**Issue by ghost** [titobrasolin/Drupal7.Services#5]
This is the only I found to contact you... Can you please update the Drupal-Ubuntu introduction document at Ubuntu.com that you wrote so it would also be in line with the new features of Drupal 8?

https://help.ubuntu.com/community/Drupal

**Comment by titobrasolin** [comment]
Hi @Benosika Unfortunately I'm not a Drupal 8 expert but I will definitely study it and possibly will write about it in the near future. Thanks for your reminder.

Tito
