### ISSUE TITLE
Retrieving custom fields

### ISSUE THREAD

**Issue by ibuildit** [titobrasolin/Drupal7.Services#6]
How do you go about retrieving a custom field? The "title", etc, are straight forward to get and map to a BaseNode. But custom fields...? =)

When I make a dump on it, I'm getting a hashtable that contains a hashtable with an Object[]

I have been able to map the field in the BaseNode, but I don't know what to do with the generic Object[] containing the string value I'm interested in.

For example:

```
field_risk_trailing_trigger_1 : [XmlRpcStruct]: hashcode { 34013913 }
{
    und : [Object[]]: hashcode { 34013913 }
    {
        300
    }
}
```

**Comment by ibuildit** [comment]
I am getting closer (but I don't know if this is the recommended way).

var node = riskNode.ToBaseNode();
IDictionary xml = (IDictionary)node.field_risk_trailing_trigger_2;
Object lastone = xml["und"];
WriteLine(lastone.DumpToString());

Results in:

[Object[]]: hashcode { 58204539 }
{
    500
}

....hmmm...

**Comment by titobrasolin** [comment]
Consider this field, as returned by `NodeRetrieve`:

```
    field_risk_welcome_message : [XmlRpcStruct]: hashcode { 30631159 }
    {
        und : [Object[]]: hashcode { 30631159 }
        {
            [XmlRpcStruct]: hashcode { 757602046 }
            {
                value : A MESSAGE!
                format : 
                safe_value : A MESSAGE!
            }
        }
    }
```

Maybe it's slightly more readable in JSON:

``` json
   "field_risk_welcome_message":{
      "und":[
         {
            "value":"A MESSAGE!",
            "format":"",
            "safe_value":"A MESSAGE!"
         }
      ]
   }
```

You can model it e.g. like this:

``` csharp
        public class text_long
        {
            public string value { get; set; }
            public string format { get; set; }
            public string safe_value { get; set; }
        }
        public class risk_welcome_message
        {
            public text_long[] und { get; set; }
        }
        public class MyDrupalNode : BaseNode
        {
            public risk_welcome_message field_risk_welcome_message { get; set; }
        }
```

Just try and convert your NodeRetrieve response like this:

``` csharp
            var n = drupal.NodeRetrieve(1);

            var ser = new JavaScriptSerializer();
            var myNode = ser.Deserialize<MyDrupalNode>(ser.Serialize(n));
```

**Comment by ibuildit** [comment]
Thanks a lot Tito. That worked.
I used the ToBaseNode() functionality, that worked great.

WriteLine(riskNode.ToBaseNode().field_risk_locked_out_message.und[0].value);

For Drupal integers that only has one value, such as:

field_risk_trailing_trigger_2 : [XmlRpcStruct]: hashcode { 3663598 }
    {
        und : [Object[]]: hashcode { 3663598 }
        {
            500
        }
    }

I did the same but only set a "value" in the class as such:

   public class risk_trailing_trigger_2
    {
        public integer[] und { get; set; }
    }

```
public class integer
{
    public string value { get; set; }
}
```

Once again, thanks a lot for your support. This was really a brick wall but now it's clear.

When I have pieced my app together I'll help you out with some documentation.

Cheers!

**Comment by ibuildit** [comment]
In case anyone wonders how to use ToBaseNode with new nodetypes, in the ExtensionMethods.cs you simply add them like this:

I also added the various drupal data types to the basenode class (such as integer, long_text, date, etc) as classes as per above message.

```
    public static BaseNode ToBaseNode(this IDictionary value)
    {
        return ConvertToType<BaseNode>(value);
    }

    public static RiskProfileNode ToRiskProfile(this IDictionary value)
    {
        return ConvertToType<RiskProfileNode>(value);
    }

    public static TradingAccountNode ToTradingAccount(this IDictionary value)
    {
        return ConvertToType<TradingAccountNode>(value);
    }
```

**Comment by ibuildit** [comment]
I added a new documentation page to the Wiki here:

https://github.com/titobrasolin/Drupal7.Services/wiki/Implement-new-field-types

**Comment by ibuildit** [comment]
See/Follow this issue on how to do it the opposite way - updating a field in a node object that is not just a simple string:
[https://github.com/titobrasolin/Drupal7.Services/issues/14](https://github.com/titobrasolin/Drupal7.Services/issues/14) (Wiki page coming when issue is fixed)
