### ISSUE TITLE
Retrieving custom User fields

### ISSUE THREAD

**Issue by ibuildit** [titobrasolin/Drupal7.Services#9]
Custom user fields are missing in the XmlRpcStruct that is returned. Do you know how to access these?

thanks

**Comment by titobrasolin** [comment]
Good point @ibuildit I'm investigating the issue and will publish an update as soon as possible.

**Comment by titobrasolin** [comment]
Just pushed an update: `UserIndex` and `UserRetrieve` now return `IDictionary`.

``` csharp
var items = drupal.UserIndex(0, "*", null, 20);
Debug.Print(items[0].ConvertToType<BaseUser>().DumpToString());
```

**Comment by ibuildit** [comment]
Very cool, thanks. I will try it out today. So if I understand this correctly, basically as long as you get the "Drupal Commands" to return an IDictionary, any fieldable entity (i.e. Commerce Order) could be used with ConvertToType?

**Comment by ibuildit** [comment]
Confirming that this is working, good job. I will add a Wiki entry as soon as possible.
